Only allow runing pot as root, protect jails dir

diff --git a/bin/pot b/bin/pot
--- a/bin/pot
+++ b/bin/pot
@@ -28,6 +28,12 @@
 # OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+# pot must run as root
+if [ "$(/usr/bin/id -u)" -ne 0 ]; then
+    2>&1 echo "Error: $0 must be run as root"
+    exit 1
+fi
+
 # Force ifconfig into expected format
 export IFCONFIG_FORMAT=addr:default
 
