create,clone: network paramater validation refactored
    create,clone: adopt validate_network_param
    	create: internal simplificationa (ipaddr empty is inherit)
    	adjust tests accordingly
    network: validate_network_param
    	create a unique routine to validate network parameters provided
    	to create and clone
    	add tests
    network.sh: new collection of network related shell routines
    	common: remove routines now in network.sh
    	tests: fix all tests
    	pot: automatically include network.sh
    Refreshed shunit2 import

diff --git a/bin/pot b/bin/pot
--- a/bin/pot
+++ b/bin/pot
@@ -42,7 +42,7 @@ else
 fi
 
 if [ ! -d "${_POT_INCLUDE}" ]; then
-	echo "Fatal error! Not able to find the subroutines dir on ${_POT_PREFIX}!"
+	echo "Fatal error! Not able to find the subroutines dir on ${_POT_INCLUDE}!"
 	exit 1
 fi
 
@@ -53,6 +53,12 @@ if [ ! -r "${_POT_INCLUDE}/common.sh" ]; then
 	exit 1
 fi
 . "${_POT_INCLUDE}/common.sh"
+
+if [ ! -r "${_POT_INCLUDE}/network.sh" ]; then
+	echo "Fatal error! Not able to find network subroutines on ${_POT_INCLUDE}!"
+	exit 1
+fi
+. "${_POT_INCLUDE}/network.sh"
 
 # loading configuration
 if [ -r "$_POT_ETC/pot.default.conf" ]; then
diff --git a/tests/shunit/test_runner b/tests/shunit/test_runner
--- a/tests/shunit/test_runner
+++ b/tests/shunit/test_runner
@@ -3,7 +3,7 @@
 #
 # Unit test suite runner.
 #
-# Copyright 2008-2017 Kate Ward. All Rights Reserved.
+# Copyright 2008-2018 Kate Ward. All Rights Reserved.
 # Released under the Apache 2.0 license.
 #
 # Author: kate.ward@forestent.com (Kate Ward)
@@ -17,25 +17,31 @@
 #   shellcheck disable=SC1090,SC1091
 # expr may be antiquated, but it is the only solution in some cases.
 #   shellcheck disable=SC2003
+# $() are not fully portable (POSIX != portable).
+#   shellcheck disable=SC2006
 
 # Return if test_runner already loaded.
 [ -z "${RUNNER_LOADED:-}" ] || return 0
 RUNNER_LOADED=0
 
-RUNNER_ARGV0=$(basename "$0")
+RUNNER_ARGV0=`basename "$0"`
 RUNNER_SHELLS='/bin/sh ash /bin/bash /bin/dash /bin/ksh /bin/pdksh /bin/zsh'
 RUNNER_TEST_SUFFIX='_test.sh'
+true; RUNNER_TRUE=$?
+false; RUNNER_FALSE=$?
 
 runner_warn() { echo "runner:WARN $*" >&2; }
+runner_error() { echo "runner:ERROR $*" >&2; }
 runner_fatal() { echo "runner:FATAL $*" >&2; exit 1; }
 
 runner_usage() {
   echo "usage: ${RUNNER_ARGV0} [-e key=val ...] [-s shell(s)] [-t test(s)]"
 }
 
-_runner_tests() { echo *${RUNNER_TEST_SUFFIX}; }
+_runner_tests() { echo ./*${RUNNER_TEST_SUFFIX} |sed 's#./##g'; }
 _runner_testName() {
-  _runner_testName_=$(expr "${1:-}" : "\(.*\)${RUNNER_TEST_SUFFIX}")
+  # shellcheck disable=SC1117
+  _runner_testName_=`expr "${1:-}" : "\(.*\)${RUNNER_TEST_SUFFIX}"`
   if [ -n "${_runner_testName_}" ]; then
     echo "${_runner_testName_}"
   else
@@ -61,8 +67,8 @@ main() {
   while getopts 'e:hs:t:' opt; do
     case ${opt} in
       e)  # set an environment variable
-        key=$(expr "${OPTARG}" : '\([^=]*\)=')
-        val=$(expr "${OPTARG}" : '[^=]*=\(.*\)')
+        key=`expr "${OPTARG}" : '\([^=]*\)='`
+        val=`expr "${OPTARG}" : '[^=]*=\(.*\)'`
         # shellcheck disable=SC2166
         if [ -z "${key}" -o -z "${val}" ]; then
           runner_usage
@@ -78,15 +84,15 @@ main() {
       *) runner_usage; exit 1 ;;
     esac
   done
-  shift "$(expr ${OPTIND} - 1)"
+  shift "`expr ${OPTIND} - 1`"
 
   # Fill shells and/or tests.
   shells=${shells:-${RUNNER_SHELLS}}
-  tests=${tests:-$(_runner_tests)}
+  [ -z "${tests}" ] && tests=`_runner_tests`
 
   # Error checking.
   if [ -z "${tests}" ]; then
-    th_error 'no tests found to run; exiting'
+    runner_error 'no tests found to run; exiting'
     exit 1
   fi
 
@@ -96,10 +102,10 @@ main() {
 #
 
 $ uname -mprsv
-$(uname -mprsv)
+`uname -mprsv`
 
-OS Name: $(versions_osName)
-OS Version: $(versions_osVersion)
+OS Name: `versions_osName`
+OS Version: `versions_osVersion`
 
 ### Test run info.
 shells: ${shells}
@@ -110,6 +116,7 @@ for key in ${env}; do
 done
 
 # Run tests.
+runner_passing_=${RUNNER_TRUE}
 for shell in ${shells}; do
   echo
 
@@ -123,25 +130,25 @@ EOF
     # Check for existence of shell.
     shell_bin=${shell}
     shell_name=''
-    shell_present=${FALSE}
+    shell_present=${RUNNER_FALSE}
     case ${shell} in
       ash)
-        shell_bin=$(which busybox)
-        [ $? -eq "${TRUE}" ] && shell_present="${TRUE}"
-        shell_bin="${shell_bin} ash"
+        shell_bin=`command -v busybox`
+        [ $? -eq "${RUNNER_TRUE}" ] && shell_present="${RUNNER_TRUE}"
+        shell_bin="${shell_bin:+${shell_bin} }ash"
         shell_name=${shell}
         ;;
       *)
-        [ -x "${shell_bin}" ] && shell_present="${TRUE}"
-        shell_name=$(basename "${shell}")
+        [ -x "${shell_bin}" ] && shell_present="${RUNNER_TRUE}"
+        shell_name=`basename "${shell}"`
         ;;
     esac
-    if [ "${shell_present}" -eq "${FALSE}" ]; then
+    if [ "${shell_present}" -eq "${RUNNER_FALSE}" ]; then
       runner_warn "unable to run tests with the ${shell_name} shell"
       continue
     fi
 
-    shell_version=$(versions_shellVersion "${shell}")
+    shell_version=`versions_shellVersion "${shell}"`
 
     echo "shell name: ${shell_name}"
     echo "shell version: ${shell_version}"
@@ -149,12 +156,15 @@ EOF
     # Execute the tests.
     for t in ${tests}; do
       echo
-      echo "--- Executing the '$(_runner_testName "${t}'")' test suite. ---"
+      echo "--- Executing the '`_runner_testName "${t}"`' test suite. ---"
       # ${shell_bin} needs word splitting.
       #   shellcheck disable=SC2086
       ( exec ${shell_bin} "./${t}" 2>&1; )
+      test "${runner_passing_}" -eq ${RUNNER_TRUE} -a $? -eq ${RUNNER_TRUE}
+      runner_passing_=$?
     done
   done
+  return ${runner_passing_}
 }
 
 # Execute main() if this is run in standalone mode (i.e. not from a unit test).
